### ISSUE TITLE
Using a template with single quote fails

### ISSUE THREAD

**Issue by baywet** [yosida95/uritemplate#14]
The follow code

```golang
uriTemplate, err := template.New("{+baseurl}/reports/getActiveUserDetail(period='{period}')")
```

fails with the error

```
errors.errorString{s:"uritemplate:72:invalid literals"}
```

according to

> If the literal character is allowed anywhere in the URI syntax (unreserved / reserved / pct-encoded ), then it is copied directly to the result string.

https://datatracker.ietf.org/doc/html/rfc6570#section-3.1

single quote being a reserved literal in the URI spec, it should be copied as is (and therefore accepted).

After testing the sample template with [a dotnet equivalent library](https://github.com/tavis-software/Tavis.UriTemplates) and a [java equivalent library](https://github.com/hal4j/uritemplate) parses the template properly.

Removing the quotes from the template also results in a successful parsing.

I believe an entry should be added here, but before I submitted any pull request I wanted to get a confirmation on the analysis.

https://github.com/yosida95/uritemplate/blob/fa7d6df706b972aab27d83eb70e9f7df6696cba5/parse.go#L42

**Comment by baywet** [comment]
CC @yosida95

**Comment by yosida95** [comment]
Sorry for the late reply. I think the current implementation works fine as per the URI Template spec.

The syntax of the URI template is defined in $2 as follows. Please note single quotation marks are explicitly excluded.

>      URI-Template  = *( literals / expression )
>      (snip)
>      literals      =  %x21 / %x23-24 / %x26 / %x28-3B / %x3D / %x3F-5B
>                    /  %x5D / %x5F / %x61-7A / %x7E / ucschar / iprivate
>                    /  pct-encoded
>                         ; any Unicode character except: CTL, SP,
>                         ;  DQUOTE, "'", "%" (aside from pct-encoded),
>                         ;  "<", ">", "\", "^", "`", "{", "|", "}"
>
> -- https://datatracker.ietf.org/doc/html/rfc6570#section-2

As single quotation marks are not allowed in a literal part, I think raising an error while parsing is the correct behavior. 

I understood the quote from §3 you mentioned above like "If the character of a literal part is contained in unreserved, reserved or pct-encoded then copy it as-is, otherwise do pct-encoding". 

I'm not a native English speaker, my understanding may be wrong. Please feel free to point out any misunderstandings.

**Comment by baywet** [comment]
Thanks for the reply!
From the paragraph right above this notation

>  The characters outside of expressions in a URI Template string are
   intended to be copied literally to the URI reference if the character
   is allowed in a URI...

' is a character that's allowed in a URI without needing to be encoded.

It does appear the spec contradicts itself right here, as well as here https://datatracker.ietf.org/doc/html/rfc6570#section-3.1

Since 2 parts of the spec indicate that single quotes are allowed, and only one says they are not, and since other libraries accept the single quote, I'd argue we should align on that behaviour and accept the single quote in this library as well.

Lastly you can also validate with this tool
https://www.utilities-online.info/uritemplate

```
{+baseurl}/reports/getActiveUserDetail(period='{period}')
```

```json
{
  "baseurl": "https://localhost",
  "period" : "2D"
}
```

**Comment by baywet** [comment]
Thank you for the extensive reply.
We could probably percent encode the single quotes but I'm not sure this is the right thing to do.
We've [opened an issue](https://github.com/uri-templates/uritemplate-test/issues/51) on the canonical test suite for the spec to request a clarification from the spec authors (and a test case to be added). Let's see what they say!

Additionally, the [python library](https://github.com/python-hyper/uritemplate/blob/49ecc93ead0d6b377830c2619fedc3ad5ef4451f/uritemplate/variable.py#L52) which has been developed by the authors of the spec, [includes the reserved range from 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-2.2) to be passed through. And that range differs from that library.

I'd avoid introducing another method in this library for custom behaviour as it's going to be detrimental for these reasons:
- Augmented maintenance workload for you (more code, and custom behaviour)
- Requires the library users to have a deep understanding of the spec, which makes the whole point of this lib moot : not having to.

**Comment by baywet** [comment]
Hi @yosida95 
We've had a conclusive answer from the specification owners and they [agreed this is a mistake in the spec](https://github.com/uri-templates/uritemplate-test/issues/51#issuecomment-1099346392).
I'm in the process of getting an errata through.
I've also submitted a PR to the [canonical test cases](https://github.com/uri-templates/uritemplate-test/pull/53)
And lastly I've submitted a PR here to address the implementation, see #15.
Thanks for you help and please review it at your earliest convenience!

**Comment by yosida95** [comment]
Thank you and your colleages for the clarification work! I'll review your PR soon.
